### PR TITLE
New hiring page (closes #273)

### LINKED ISSUE #273: New hiring page - implementazione
[Project card](https://github.com/buildo/buildo.io/projects/1?fullscreen=true#card-17698822)

vedi https://app.moqups.com/S794QUeE3G/view/page/a69cde27e

mockup per implementazione: https://github.com/buildo/buildo.io/projects/1

### PR DESCRIPTION
**Pull request by gabro**
Closes #273

See mockup: https://share.goabstract.com/68803a41-29db-44d9-96f2-1a341857ff3b

### CODE REVIEW

**Comment by ecamellini** [comment]
@alessandravilla I miss just a few things and then it should be ready:
* the image for "Continuously Improving" in PNG format instead of JPG
* the entire background image for "Open Positions": the SVG that there is now is cut by the borders of the page:

**Comment by alessandravilla** [comment]
ok, ora ti preparo gli export esatti.
Nella sezione "Continuously improving" se collassato c'è icona del meno al posto di quella del +
image

**Comment by alessandravilla** [comment]
image
scritta è molto sgranata

**Comment by alessandravilla** [comment]
image
cta rotta su mobile

**Pull request merged**
